#!/usr/bin/env python3
"""Generate the docs-site pages whose content lives elsewhere in the repository.

Three pages are rendered from files that are already the source of truth, so
that the site cannot drift from them:

  runbooks/index.md       the research gallery, from the executed notebooks in
                          notebooks/python/NN_*.ipynb and the figures they export
                          to docs-site/public/figures/notebooks/
  project/performance.md  from benchmarks/*.json, benchmarks/data_processing/latest.json
                          and the criterion benches in crates/openquant/benches/
  project/changelog.md    from CHANGELOG.md

Modes:

  --check (default, CI)  exit non-zero if any page differs from what the sources give
  --write                rewrite the pages that differ

Every page carries `status: generated` and a `last_generated` stamp. The stamp is
ignored when comparing, and a page whose content has not changed keeps its old
stamp, so re-running this script is a no-op unless a source moved.

What the gallery reads from a notebook (the runbook sections of the notebook
contract, see notebooks/python/README.md):

  title       the first `# ` heading, without a leading "Runbook: " or "API tour: "
  hypothesis  the `## Hypothesis` section: its `**H1 ...**` paragraphs and bullets
              (the whole section when there are none)
  figures     every `figure("nbNN-...")` call in a code cell, alt text from the
              exported SVG's <title>
  result      the stdout of the code cells under `## Analysis` (the executed
              verdict); if there is none, the Analysis paragraphs whose bold lead
              names a hypothesis (`**H1 ...**`, `**Both hypotheses ...**`); failing
              that, the first Analysis paragraph
  decision    the `## Promotion decision` section

A notebook with both a Hypothesis and a Promotion decision section is listed as a
runbook; the others are listed below them with their summary paragraph and figures.
Standard library only, so it runs on the CI runner's python3.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs-site" / "src" / "content" / "docs"
NOTEBOOKS = ROOT / "notebooks" / "python"
FIGURES = ROOT / "docs-site" / "public" / "figures" / "notebooks"
RUNBOOK_PAGES = DOCS / "runbooks"
BENCH = ROOT / "benchmarks"
BENCH_SRC = ROOT / "crates" / "openquant" / "benches"
CHANGELOG = ROOT / "CHANGELOG.md"
REPO_URL = "https://github.com/Open-Quant/openquant"
SCRIPT = "scripts/docs/generate_site_pages.py"

STAMP_RE = re.compile(r"^last_generated: .*$", re.MULTILINE)


class SourceError(Exception):
    """A source file does not have the shape this script needs."""


# --------------------------------------------------------------------------- shared


def frontmatter(
    *, title: str, description: str, generated_from: str, order: int, stamp: str
) -> str:
    return (
        "---\n"
        f"title: {json.dumps(title, ensure_ascii=False)}\n"
        f"description: {json.dumps(description, ensure_ascii=False)}\n"
        "status: generated\n"
        f"generated_from: {json.dumps(generated_from)}\n"
        f"last_generated: '{stamp}'\n"
        "audience:\n"
        "  - quant-dev\n"
        "  - platform-engineering\n"
        "sidebar:\n"
        f"  order: {order}\n"
        "---\n\n"
        f"<!-- Generated by {SCRIPT} from {generated_from}. Do not edit by hand:\n"
        f"     change the source and run `python3 {SCRIPT} --write`. -->\n\n"
    )


def figure_pair(name: str, alt: str) -> str:
    alt = alt.replace('"', "&quot;")
    return (
        f'<img class="dark:sl-hidden" src="/figures/notebooks/{name}-light.svg" alt="{alt}" />\n'
        f'<img class="light:sl-hidden" src="/figures/notebooks/{name}-dark.svg" alt="{alt}" />\n'
    )


def fmt_ms(value: float) -> str:
    if value >= 100:
        return f"{value:,.1f}"
    if value >= 1:
        return f"{value:,.2f}"
    return f"{value:,.3f}"


# --------------------------------------------------------------------------- notebooks


def cell_text(cell: dict) -> str:
    src = cell.get("source", "")
    return "".join(src) if isinstance(src, list) else src


def split_sections(cells: list[dict]) -> dict[str, list[dict]]:
    """Cells grouped by the `## ` heading they fall under ('' before the first).

    A markdown cell that opens with `## Name` starts section `Name`; the rest of
    that cell's text belongs to the section (the heading line is dropped).
    """
    sections: dict[str, list[dict]] = {"": []}
    current = ""
    for cell in cells:
        text = cell_text(cell)
        if cell.get("cell_type") == "markdown":
            m = re.match(r"^## (.+?)\s*$", text.splitlines()[0] if text else "")
            if m:
                current = m.group(1).strip()
                rest = "\n".join(text.splitlines()[1:]).strip("\n")
                sections.setdefault(current, [])
                if rest.strip():
                    sections[current].append({**cell, "source": rest})
                continue
        sections.setdefault(current, []).append(cell)
    return sections


def markdown_of(cells: list[dict]) -> str:
    return "\n\n".join(
        cell_text(c).strip() for c in cells if c.get("cell_type") == "markdown"
    ).strip()


def paragraphs(md: str) -> list[str]:
    return [p.strip("\n") for p in re.split(r"\n\s*\n", md) if p.strip()]


def hypothesis_blocks(md: str) -> str:
    """The `**H<n>` paragraphs and list items (with their continuation lines)."""
    lines = md.splitlines()
    out: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        item = re.match(r"^- \*\*H\d", line)
        para = re.match(r"^\*\*H\d", line)
        if item or para:
            block = [line]
            i += 1
            while i < len(lines):
                nxt = lines[i]
                if not nxt.strip():
                    break
                if item and not nxt.startswith((" ", "\t")):
                    break
                block.append(nxt)
                i += 1
            if para and out:
                out.append("")
            out.extend(block)
            continue
        i += 1
    return "\n".join(out).strip()


def stdout_of(cells: list[dict]) -> str:
    chunks = []
    for cell in cells:
        if cell.get("cell_type") != "code":
            continue
        for output in cell.get("outputs", []):
            if output.get("output_type") == "stream" and output.get("name") == "stdout":
                text = output.get("text", "")
                chunks.append("".join(text) if isinstance(text, list) else text)
    return "".join(chunks).rstrip()


def analysis_result(cells: list[dict]) -> tuple[str, str]:
    """('text', verdict printout) or ('markdown', paragraphs)."""
    printed = stdout_of(cells)
    if printed:
        return "text", printed
    paras = paragraphs(markdown_of(cells))
    names_hypothesis = re.compile(r"^\*\*[^*]*(\bH\d|[Hh]ypothes)")
    picked: list[str] = []
    for p in paras:
        if names_hypothesis.match(p):
            picked.append(p)
        elif picked:
            break
    if picked:
        return "markdown", "\n\n".join(picked)
    if paras:
        return "markdown", paras[0]
    raise SourceError("the Analysis section has neither printed output nor prose")


FIGURE_CALL = re.compile(r"""\bfigure\(\s*["']([a-z0-9][a-z0-9-]*)["']""")


def figures_of(cells: list[dict], nb_name: str) -> list[tuple[str, str]]:
    found: list[tuple[str, str]] = []
    for cell in cells:
        if cell.get("cell_type") != "code":
            continue
        for name in FIGURE_CALL.findall(cell_text(cell)):
            if any(name == n for n, _ in found):
                continue
            light = FIGURES / f"{name}-light.svg"
            dark = FIGURES / f"{name}-dark.svg"
            if not (light.exists() and dark.exists()):
                raise SourceError(
                    f"{nb_name} draws figure {name!r} but {light.relative_to(ROOT)} "
                    f"or its -dark twin is missing; run `just notebooks-run`"
                )
            m = re.search(r"<title>(.*?)</title>", light.read_text(encoding="utf-8"), re.S)
            alt = (m.group(1).strip() if m else "") or name
            alt = alt.replace("&lt;", "<").replace("&gt;", ">").replace("&amp;", "&")
            found.append((name, " ".join(alt.split())))
    return found


def runbook_page_for(nb_file: str) -> str | None:
    """Slug of the runbook page that links to this notebook, if exactly one does."""
    needle = f"notebooks/python/{nb_file}"
    hits = [
        p
        for p in sorted(RUNBOOK_PAGES.glob("*.md"))
        if p.name != "index.md" and needle in p.read_text(encoding="utf-8")
    ]
    if len(hits) > 1:
        raise SourceError(f"{needle} is referenced by several runbook pages: {hits}")
    return f"/runbooks/{hits[0].stem}/" if hits else None


def notebook_entry(path: Path) -> dict:
    nb = json.loads(path.read_text(encoding="utf-8"))
    cells = nb.get("cells", [])
    if not cells:
        raise SourceError(f"{path.name} has no cells")
    head = cell_text(cells[0])
    m = re.match(r"^# (.+?)\s*$", head.splitlines()[0] if head else "")
    if not m:
        raise SourceError(f"{path.name}: the first cell does not open with a `# ` title")
    title = re.sub(r"^(Runbook|API tour):\s*", "", m.group(1)).strip()
    title = title[0].upper() + title[1:]
    intro = [
        p
        for p in paragraphs("\n".join(head.splitlines()[1:]))
        if not p.startswith(">") and not p.startswith("#")
    ]
    sections = split_sections(cells)
    entry = {
        "file": path.name,
        "number": path.name.split("_", 1)[0],
        "title": title,
        "summary": intro[0] if intro else "",
        "figures": figures_of(cells, path.name),
        "page": runbook_page_for(path.name),
        "runbook": "Hypothesis" in sections and "Promotion decision" in sections,
    }
    if entry["runbook"]:
        hyp_md = markdown_of(sections["Hypothesis"])
        entry["hypothesis"] = hypothesis_blocks(hyp_md) or hyp_md
        if "Analysis" not in sections:
            raise SourceError(f"{path.name} has a Promotion decision but no Analysis section")
        entry["result"] = analysis_result(sections["Analysis"])
        decision = paragraphs(markdown_of(sections["Promotion decision"]))
        if not decision:
            raise SourceError(f"{path.name}: the Promotion decision section is empty")
        entry["decision"] = decision
    return entry


def render_gallery(entries: list[dict], stamp: str) -> str:
    runbooks = [e for e in entries if e["runbook"]]
    others = [e for e in entries if not e["runbook"]]
    nb_url = f"{REPO_URL}/blob/main/notebooks/python"
    out = [
        frontmatter(
            title="Research gallery",
            description=(
                "Every research runbook in notebooks/python: its pre-registered hypothesis, "
                "figures, result and promotion decision, taken from the executed notebooks."
            ),
            generated_from="notebooks/python/*.ipynb",
            order=0,
            stamp=stamp,
        )
    ]
    out.append(
        ":::caution[SYNTHETIC data]\n"
        "Every committed result on this page is computed on simulated series or on the committed "
        "SYNTHETIC sample `SYN_A`..`SYN_E` (see `DATA_SOURCES.md`). None of it describes a real "
        "market.\n"
        ":::\n"
    )
    out.append(
        "A runbook is a notebook that states a falsifiable hypothesis before it is run, tests it "
        "on data where the right answer is known, and ends with a promotion decision: what, if "
        "anything, later work should adopt. The notebooks are executed in CI "
        "(`.github/workflows/notebooks.yml`) and committed with their outputs, and this page is "
        "rebuilt from those outputs, so each result below is the text the notebook printed or "
        "wrote on its last committed run. The hypotheses are quoted in part (the `H1`, `H2`, ... "
        "statements); each runbook's page and notebook have the full pre-registration, the method "
        "and the controls.\n"
    )
    rows = ["| # | Runbook | Figures | Decision |", "| --- | --- | ---: | --- |"]
    for e in runbooks:
        link = e["page"] or f"{nb_url}/{e['file']}"
        lead = re.match(r"^\*\*(.+?)\*\*", e["decision"][0], re.S)
        verdict = lead.group(1).rstrip(".") if lead else e["decision"][0].split(". ")[0]
        verdict = " ".join(verdict.split())
        verdict = re.sub(r"^Decision:\s*", "", verdict)
        verdict = verdict[0].upper() + verdict[1:]
        rows.append(f"| {e['number']} | [{e['title']}]({link}) | {len(e['figures'])} | {verdict} |")
    out.append("\n".join(rows) + "\n")

    for e in runbooks:
        out.append(f"## {e['number']} · {e['title']}\n")
        links = []
        if e["page"]:
            links.append(f"[Runbook page]({e['page']})")
        links.append(f"[notebook `{e['file']}`]({nb_url}/{e['file']})")
        out.append(" · ".join(links) + "\n")
        out.append("### Hypothesis\n")
        out.append(e["hypothesis"] + "\n")
        for name, alt in e["figures"]:
            out.append(figure_pair(name, alt))
        out.append("### Result\n")
        kind, body = e["result"]
        if kind == "text":
            out.append("As printed by the notebook's Analysis section:\n")
            out.append("```text\n" + body + "\n```\n")
        else:
            out.append(body + "\n")
        out.append("### Promotion decision\n")
        out.append(e["decision"][0] + "\n")
        if len(e["decision"]) > 1:
            out.append("<details>\n<summary>The rest of the decision</summary>\n")
            out.append("\n\n".join(e["decision"][1:]) + "\n")
            out.append("</details>\n")

    if others:
        out.append("## API tours\n")
        out.append(
            "These notebooks have no pre-registered hypothesis and promotion decision, so they are "
            "not runbooks: they show how a few calls fit together on synthetic data and claim "
            "nothing (see the [notebook contract](/workflows/research-notebook-contract/)). They "
            "are executed and checked in CI in the same way.\n"
        )
        for e in others:
            out.append(f"### {e['number']} · {e['title']}\n")
            out.append(f"[notebook `{e['file']}`]({nb_url}/{e['file']})\n")
            if e["summary"]:
                out.append(e["summary"] + "\n")
            for name, alt in e["figures"]:
                out.append(figure_pair(name, alt))
    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------- benchmarks

# What each committed criterion benchmark measures. Every benchmark in the
# manifest must have an entry, so a new benchmark cannot reach the page
# undescribed. Keep in step with crates/openquant/benches/.
BENCH_DESCRIPTIONS = {
    "structural_breaks_get_sadf_sm_power": (
        "`structural_breaks::get_sadf`, `sm_power` model with constant, on 320 log prices, "
        "minimum window 20, 5 fixed lags"
    ),
    "bet_sizing_bet_size_reserve_fit": (
        "`bet_sizing::bet_size_reserve_full` on 500 synthetic events: fits the EF3M mixture "
        "(100 runs) and sizes every bet"
    ),
    "bet_sizing_bet_size_reserve_reuse_fit": (
        "`bet_sizing::bet_size_reserve` on the same 500 events, reusing already-fitted "
        "mixture parameters"
    ),
    "synthetic_ticker_ewma_100k": "`util::fast_ewma::ewma`, window 64, on 100,000 prices",
    "synthetic_ticker_risk_metrics_var_es_cdar": (
        "`RiskMetrics` value at risk, expected shortfall and conditional drawdown at risk "
        "(5%) on 119,999 returns"
    ),
    "synthetic_ticker_seq_bootstrap_2k_600": (
        "`sampling::seq_bootstrap`: 240 draws from an indicator matrix of 600 labels over "
        "2,000 bars"
    ),
    "synthetic_ticker_pipeline_end_to_end": (
        "EWMA, VaR/ES/CDaR, a 3×3 covariance and portfolio variance, and a 200-draw "
        "sequential bootstrap (360 labels over 1,200 bars) on 20,000 prices, in one pass"
    ),
}

BENCH_CALL = re.compile(r"""bench_function\(\s*"([^"]+)\"""")
GROUP_CALL = re.compile(r"""benchmark_group\(\s*"([^"]+)\"""")


def bench_sources() -> tuple[dict[str, str], list[tuple[str, str]]]:
    """Benchmark key -> bench file, and (name, file) for every group/function found."""
    by_key: dict[str, str] = {}
    found: list[tuple[str, str]] = []
    for path in sorted(BENCH_SRC.glob("*.rs")):
        text = path.read_text(encoding="utf-8")
        for name in BENCH_CALL.findall(text):
            by_key[name.replace("/", "_")] = path.name
            found.append((name, path.name))
        for name in GROUP_CALL.findall(text):
            found.append((f"{name}/*", path.name))
    return by_key, found


def render_performance(stamp: str) -> str:
    latest = json.loads((BENCH / "latest_benchmarks.json").read_text(encoding="utf-8"))
    baseline = json.loads((BENCH / "baseline_benchmarks.json").read_text(encoding="utf-8"))
    manifest = json.loads((BENCH / "benchmark_manifest.json").read_text(encoding="utf-8"))
    overrides = json.loads((BENCH / "threshold_overrides.json").read_text(encoding="utf-8"))
    data = json.loads((BENCH / "data_processing" / "latest.json").read_text(encoding="utf-8"))
    by_key, found = bench_sources()

    missing = [k for k in manifest if k not in BENCH_DESCRIPTIONS]
    if missing:
        raise SourceError(f"add a BENCH_DESCRIPTIONS entry in {SCRIPT} for: {', '.join(missing)}")
    unknown = [k for k in manifest if k not in by_key]
    if unknown:
        raise SourceError(f"manifest benchmarks with no bench_function in benches/: {unknown}")

    workflow = (ROOT / ".github" / "workflows" / "benchmark-regression.yml").read_text(
        encoding="utf-8"
    )
    m = re.search(r"--max-regression-pct\s+([0-9.]+)", workflow)
    if not m:
        raise SourceError("could not read --max-regression-pct from benchmark-regression.yml")
    gate_pct = float(m.group(1))  # the gate's default threshold, read from the workflow

    when = latest.get("generated_at_utc", "")[:10] or "unknown date"
    commit = latest.get("commit") or "unrecorded"
    commit_md = f"[`{commit}`]({REPO_URL}/commit/{commit})" if latest.get("commit") else commit

    out = [
        frontmatter(
            title="Performance",
            description=(
                "Committed criterion and Python benchmark results, what each benchmark "
                "measures, and how CI gates regressions."
            ),
            generated_from="benchmarks/",
            order=2,
            stamp=stamp,
        )
    ]
    out.append(
        "The numbers below are the benchmark results committed in `benchmarks/`. They are "
        "one run on one machine, and the files do not record which machine, so read them as "
        "orders of magnitude and relative costs, not as a promise about your hardware. Pull "
        "requests are not judged against them (see [Regression gate](#regression-gate)).\n"
    )
    out.append("## Rust core (criterion)\n")
    out.append(
        f"`benchmarks/latest_benchmarks.json`: {latest.get('count', len(latest['benchmarks']))} "
        f"benchmarks, collected on {when} at commit {commit_md}. Times are criterion's mean per "
        "iteration with its 95% confidence interval.\n"
    )
    rows = [
        "| Benchmark | What it measures | Mean (ms) | 95% CI (ms) | Source |",
        "| --- | --- | ---: | ---: | --- |",
    ]
    for key in sorted(latest["benchmarks"], key=lambda k: -latest["benchmarks"][k]["mean_ms"]):
        b = latest["benchmarks"][key]
        lo, hi = b["ci_lower_ns"] / 1e6, b["ci_upper_ns"] / 1e6
        src = by_key.get(key)
        src_md = (
            f"[`{src}`]({REPO_URL}/blob/main/crates/openquant/benches/{src})" if src else "—"
        )
        desc = BENCH_DESCRIPTIONS.get(key, "not in the manifest")
        rows.append(
            f"| `{key}` | {desc} | {fmt_ms(b['mean_ms'])} | "
            f"{fmt_ms(lo)}–{fmt_ms(hi)} | {src_md} |"
        )
    out.append("\n".join(rows) + "\n")

    same = latest["benchmarks"] == baseline["benchmarks"]
    if same:
        out.append(
            "`benchmarks/baseline_benchmarks.json` holds the same numbers: the baseline was "
            "last refreshed from this run.\n"
        )
    else:
        rows = ["| Benchmark | Baseline (ms) | Latest (ms) | Change |", "| --- | ---: | ---: | ---: |"]
        for key in sorted(set(baseline["benchmarks"]) & set(latest["benchmarks"])):
            b = baseline["benchmarks"][key]["mean_ms"]
            c = latest["benchmarks"][key]["mean_ms"]
            rows.append(f"| `{key}` | {fmt_ms(b)} | {fmt_ms(c)} | {(c - b) / b * 100:+.1f}% |")
        out.append(
            f"Against `benchmarks/baseline_benchmarks.json` (collected "
            f"{baseline.get('generated_at_utc', '')[:10] or 'on an unrecorded date'}):\n"
        )
        out.append("\n".join(rows) + "\n")

    not_tracked = [(n, f) for n, f in found if n.replace("/", "_") not in manifest]
    if not_tracked:
        items = ", ".join(f"`{n}` ({f})" for n, f in not_tracked)
        out.append(
            "Benchmarks that exist in `crates/openquant/benches/` but are not in "
            f"`benchmarks/benchmark_manifest.json`, so are neither committed here nor gated: "
            f"{items}. Run them with `cargo bench -p openquant --bench <file stem>`.\n"
        )

    out.append("## Python data layer\n")
    ds = data.get("dataset", {})
    out.append(
        "`benchmarks/data_processing/latest.json`, written by "
        "`python/benchmarks/benchmark_data_processing.py`: "
        f"{ds.get('symbols', '?')} symbols × {ds.get('rows_per_symbol', 0):,} rows "
        f"({ds.get('total_rows', 0):,} rows), {data.get('iterations', '?')} iterations per "
        "function. The file records neither a date nor a commit. `just py-bench-data` "
        "regenerates it (with 200,000 rows per symbol, not the size committed here).\n"
    )
    rows = [
        "| Function | Rows | Mean (ms) | p95 (ms) | Rows/s | MB/s |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for f in data.get("functions", []):
        rows.append(
            f"| `{f['name']}` | {f['rows']:,} | {fmt_ms(f['mean_ms'])} | {fmt_ms(f['p95_ms'])} | "
            f"{f['rows_per_sec']:,.0f} | {f['mb_per_sec']:,.1f} |"
        )
    out.append("\n".join(rows) + "\n")
    if not (BENCH / "data_processing" / "baseline.json").exists():
        out.append(
            "There is no committed `benchmarks/data_processing/baseline.json`, so "
            "`just py-bench-data-compare` has nothing to compare against until one is made, "
            "and no CI job runs these benchmarks.\n"
        )

    out.append("## Regression gate\n")
    rows = ["| Benchmark | Allowed slowdown |", "| --- | ---: |"]
    for key in manifest:
        rows.append(f"| `{key}` | {overrides.get(key, gate_pct):.0f}% |")
    out.append(
        "`.github/workflows/benchmark-regression.yml` runs on pull requests that touch "
        "`crates/openquant/`, the workspace manifests, the toolchain pin or the benchmark "
        "scripts. It builds the pull request's merge base and its head, runs the "
        "`perf_hotspots` and `synthetic_ticker_pipeline` benches on both **on the same runner**, "
        "and fails if a benchmark's mean slowed down by more than "
        f"{gate_pct:.0f}% (`scripts/check_bench_thresholds.py`), or by more than its entry in "
        "`benchmarks/threshold_overrides.json`. A benchmark that stops producing a result "
        "fails the gate too. Comparing base and head back to back removes the machine-to-"
        "machine variation that made a gate against the committed baseline fail on unrelated "
        "changes. Because the workflow is path-filtered, it is not suitable as a required status check.\n"
    )
    out.append("\n".join(rows) + "\n")
    out.append("## Reproduce\n")
    out.append(
        "```bash\n"
        "just bench-all      # cargo bench -p openquant --bench perf_hotspots --bench synthetic_ticker_pipeline\n"
        "just bench-collect  # target/criterion -> benchmarks/latest_benchmarks.json (manifest only)\n"
        "just bench-check    # latest vs the committed baseline, with the thresholds CI uses\n"
        "just py-bench-data  # Python data-layer benchmarks -> benchmarks/data_processing/latest.json\n"
        f"python3 {SCRIPT} --write   # re-render this page\n"
        "```\n"
    )
    out.append(
        "Refresh `benchmarks/baseline_benchmarks.json` only in a pull request that says why; "
        "a slowdown and a new baseline in the same change hides the slowdown.\n"
    )
    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------- changelog


def render_changelog(stamp: str) -> str:
    text = CHANGELOG.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or not lines[0].startswith("# "):
        raise SourceError("CHANGELOG.md must open with a `# ` title")
    body = "\n".join(lines[1:]).strip()
    # Relative links in CHANGELOG.md point into the repository; on the site they
    # have to point at GitHub.
    body = re.sub(
        r"\]\((?!https?://|#|/)([^)]+)\)", lambda m: f"]({REPO_URL}/blob/main/{m.group(1)})", body
    )
    return (
        frontmatter(
            title="Changelog",
            description="Notable changes to OpenQuant, rendered from CHANGELOG.md.",
            generated_from="CHANGELOG.md",
            order=3,
            stamp=stamp,
        )
        + body
        + "\n"
    )


# --------------------------------------------------------------------------- driver


def build_pages(stamp: str) -> dict[Path, str]:
    entries = [notebook_entry(p) for p in sorted(NOTEBOOKS.glob("[0-9][0-9]_*.ipynb"))]
    return {
        DOCS / "runbooks" / "index.md": render_gallery(entries, stamp),
        DOCS / "project" / "performance.md": render_performance(stamp),
        DOCS / "project" / "changelog.md": render_changelog(stamp),
    }


def strip_stamp(text: str) -> str:
    return STAMP_RE.sub("", text)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail if a page is stale (default)")
    mode.add_argument("--write", action="store_true", help="rewrite stale pages")
    args = parser.parse_args()

    try:
        pages = build_pages(date.today().isoformat())
    except SourceError as err:
        print(f"{SCRIPT}: {err}", file=sys.stderr)
        return 1

    stale = []
    for path, want in pages.items():
        have = path.read_text(encoding="utf-8") if path.exists() else None
        if have is not None and strip_stamp(have) == strip_stamp(want):
            continue
        stale.append(path)
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(want, encoding="utf-8")

    rel = [str(p.relative_to(ROOT)) for p in stale]
    if args.write:
        print(f"rewrote {len(rel)} page(s)" + (": " + ", ".join(rel) if rel else ""))
        return 0
    if rel:
        print(
            "generated pages are stale: " + ", ".join(rel) + f"\nrun `python3 {SCRIPT} --write`",
            file=sys.stderr,
        )
        return 1
    print(f"generated pages are current ({len(pages)} checked)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
