# Generated by scripts/generate_python_stubs.py from crates/pyopenquant/src. Do not edit.
"""Stubs for ``openquant._core.cla``."""

from collections.abc import Sequence
from typing import Any

__all__ = [
    "allocate_cla",
]

def allocate_cla(
    asset_prices: Sequence[Sequence[float]] | None = None,
    expected_returns: Sequence[float] | None = None,
    covariance_matrix: Sequence[Sequence[float]] | None = None,
    weight_bounds_lower: float | None = None,
    weight_bounds_upper: float | None = None,
    resample_by: str | None = None,
    solution: str | None = None,
    calculate_expected_returns: str = "mean",
) -> Any: ...
