# Generated by scripts/generate_python_stubs.py from crates/pyopenquant/src. Do not edit.
"""Stubs for ``openquant._core.fast_ewma``."""

from collections.abc import Sequence

__all__ = [
    "ewma",
]

def ewma(arr: Sequence[float], window: int) -> list[float]:
    """Bias-corrected exponentially weighted moving average with span `window`.

    Matches `mlfinlab.util.fast_ewma.ewma` and pandas' `ewm(span=window, adjust=True).mean()`:
    with `alpha = 2 / (window + 1)`, output `t` is the weighted mean of every value so far,
    with weight `(1 - alpha)^k` on the value `k` steps back. The first output equals the first
    input, and `window = 1` returns the input unchanged. `window` is a span, not a hard
    lookback. Values are not validated: a NaN makes that output and every later one NaN
    (pandas would skip it).

    Parameters
    ----------
    arr : list[float]
        Input series, oldest first.
    window : int
        Span of the average; must be positive.

    Returns
    -------
    list[float]
        The moving average, same length as `arr` (empty for an empty input).

    Raises
    ------
    ValueError
        If `window` is 0.
    """
