# Generated by scripts/generate_python_stubs.py from crates/pyopenquant/src. Do not edit.
"""Stubs for ``openquant._core.filters``."""

from collections.abc import Sequence

__all__ = [
    "cusum_filter_indices",
    "cusum_filter_timestamps",
    "z_score_filter_indices",
    "z_score_filter_timestamps",
]

def cusum_filter_indices(close: Sequence[float], threshold: float) -> list[int]: ...
def cusum_filter_timestamps(
    close: Sequence[float],
    timestamps: Sequence[str],
    threshold: float,
) -> list[str]: ...
def z_score_filter_indices(
    close: Sequence[float],
    mean_window: int,
    std_window: int,
    threshold: float,
) -> list[int]: ...
def z_score_filter_timestamps(
    close: Sequence[float],
    timestamps: Sequence[str],
    mean_window: int,
    std_window: int,
    threshold: float,
) -> list[str]: ...
