# Generated by scripts/generate_python_stubs.py from crates/pyopenquant/src. Do not edit.
"""Stubs for ``openquant._core.sb_bagging``."""

from collections.abc import Sequence
from typing import Any

__all__ = [
    "fit_predict_sb_classifier",
    "fit_predict_sb_regressor",
]

def fit_predict_sb_classifier(
    x: Sequence[Sequence[float]],
    y: Sequence[int],
    ind_mat: Sequence[Sequence[int]],
    n_estimators: int = 10,
    max_samples: float = 1.0,
    max_features: float = 1.0,
    random_state: int = 42,
    sample_weight: Sequence[float] | None = None,
) -> Any: ...
def fit_predict_sb_regressor(
    x: Sequence[Sequence[float]],
    y: Sequence[float],
    ind_mat: Sequence[Sequence[int]],
    n_estimators: int = 10,
    max_samples: float = 1.0,
    max_features: float = 1.0,
    random_state: int = 42,
    sample_weight: Sequence[float] | None = None,
) -> Any: ...
