#!/usr/bin/env python3
"""Generate the ``.pyi`` stubs for the compiled ``openquant._core`` extension.

The stubs are derived from the PyO3 bindings in ``crates/pyopenquant/src``: each
``#[pyfunction]``'s Rust parameter and return types are mapped to Python types, its
``#[pyo3(signature = ...)]`` supplies the defaults, and its ``///`` doc comment becomes the
stub's docstring (the same text the runtime ``__doc__`` carries). A registered
``#[pyclass]`` becomes a stub class: its ``#[new]`` is ``__new__``, its ``#[pymethods]``
are methods and its ``#[getter]``s read-only properties.

Arguments are typed by what PyO3 will *accept* (``Vec<f64>`` takes any sequence of numbers,
so ``Sequence[float]``); results by what it *produces* (``list[float]``).

    python scripts/generate_python_stubs.py          # write python/openquant/_core/*.pyi
    python scripts/generate_python_stubs.py --check  # fail if the committed stubs are stale

``python -m mypy.stubtest openquant._core`` (``just py-stubtest``; CI runs it) then checks the stubs against the
built extension.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from pyopenquant_bindings import (
    BINDINGS,
    ROOT,
    Binding,
    PyClass,
    _split_top,
    all_bindings,
    all_classes,
    type_aliases,
)

OUT_DIR = ROOT / "python" / "openquant" / "_core"
HEADER = (
    "# Generated by scripts/generate_python_stubs.py from crates/pyopenquant/src. Do not edit.\n"
)

INTS = {"i8", "i16", "i32", "i64", "i128", "isize", "u8", "u16", "u32", "u64", "u128", "usize"}
FLOATS = {"f32", "f64"}


class UnknownType(Exception):
    pass


def _strip_ref(t: str) -> str:
    t = t.strip()
    t = re.sub(r"^&\s*(?:'[a-z_]+\s+)?(?:mut\s+)?", "", t)
    return t.strip()


def _generic(t: str) -> tuple[str, list[str]] | None:
    m = re.match(r"^([A-Za-z0-9_:]+)\s*<(.*)>$", t, re.S)
    if not m:
        return None
    args = [a for a in _split_top(m.group(2)) if not a.startswith("'")]
    return m.group(1).split("::")[-1], args


def py_type(rust: str, mode: str, aliases: dict[str, str], used: set[str]) -> str:
    """Map a Rust type to a Python annotation. ``mode`` is "in" (argument) or "out" (result)."""
    t = _strip_ref(rust)
    if t in aliases:
        return py_type(aliases[t], mode, aliases, used)
    if t == "()":
        return "None"
    if t == "Self":
        used.add("Self")
        return "Self"
    if t in FLOATS:
        return "float"
    if t in INTS:
        return "int"
    if t == "bool":
        return "bool"
    if t in {"String", "str", "char"}:
        return "str"
    if t in {"PyObject", "Py<PyAny>"}:
        used.add("Any")
        return "Any"
    if t in {"PyDataFrame"}:
        used.add("polars")
        return "polars.DataFrame"
    if t.startswith("(") and t.endswith(")"):
        parts = _split_top(t[1:-1])
        return "tuple[" + ", ".join(py_type(p, mode, aliases, used) for p in parts) + "]"
    if t.startswith("[") and t.endswith("]"):
        inner = _split_top(t[1:-1], ";")[0]
        return _seq(py_type(inner, mode, aliases, used), mode, used)
    g = _generic(t)
    if g:
        head, args = g
        if head == "PyResult":
            return py_type(args[0], mode, aliases, used)
        if head in {"PyRef", "PyRefMut"} and args and args[-1].strip() == "Self":
            used.add("Self")
            return "Self"
        if head == "Option":
            return f"{py_type(args[0], mode, aliases, used)} | None"
        if head == "Vec":
            if mode == "out" and _strip_ref(args[0]) == "u8":
                return "bytes"
            return _seq(py_type(args[0], mode, aliases, used), mode, used)
        if head in {"HashMap", "BTreeMap", "IndexMap"}:
            k = py_type(args[0], mode, aliases, used)
            v = py_type(args[1], mode, aliases, used)
            if mode == "in":
                used.add("Mapping")
                return f"Mapping[{k}, {v}]"
            return f"dict[{k}, {v}]"
        if head in {"Bound", "Borrowed", "Py"}:
            inner = args[-1].split("::")[-1]
            if inner == "PyDict":
                used.add("Any")
                return "dict[str, Any]"
            if inner == "PyList":
                used.add("Any")
                return "list[Any]"
            if inner == "PyAny":
                used.add("Any")
                return "Any"
            if inner == "PyString":
                return "str"
    raise UnknownType(rust)


def _seq(inner: str, mode: str, used: set[str]) -> str:
    if mode == "in":
        used.add("Sequence")
        return f"Sequence[{inner}]"
    return f"list[{inner}]"


def py_default(expr: str) -> str:
    e = expr.strip()
    if e == "None":
        return "None"
    if e in {"true", "false"}:
        return e.capitalize()
    if re.fullmatch(r'"[^"\\]*"', e):
        return e
    m = re.fullmatch(
        r"(-?[0-9][0-9_]*(?:\.[0-9_]*)?(?:[eE][-+]?[0-9]+)?)(?:_?[iuf](?:8|16|32|64|128|size))?", e
    )
    if m:
        num = m.group(1).replace("_", "")
        if num.endswith("."):
            num += "0"
        return num
    return "..."


def _docstring(doc: str, indent: str) -> str:
    if not doc.strip():
        return ""
    body = doc.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    lines = body.split("\n")
    if len(lines) == 1:
        return f'{indent}"""{lines[0]}"""\n'
    out = [f'{indent}"""{lines[0]}']
    out += [f"{indent}{line}" if line else "" for line in lines[1:]]
    out.append(f'{indent}"""')
    return "\n".join(out) + "\n"


def render_function(
    b: Binding,
    aliases: dict[str, str],
    used: set[str],
    receiver: str | None = None,
    indent: str = "",
) -> str:
    params: list[str] = [receiver] if receiver else []
    for i, p in enumerate(b.params):
        if b.keyword_only_from is not None and i == b.keyword_only_from:
            params.append("*")
        try:
            ann = py_type(p.rust_type, "in", aliases, used)
        except UnknownType as exc:
            raise SystemExit(
                f"{b.file.name}:{b.line}: {b.name}({p.name}): no Python mapping for Rust type "
                f"{exc.args[0]!r}; teach scripts/generate_python_stubs.py:py_type about it"
            ) from None
        text = f"{p.name}: {ann}"
        if p.default is not None:
            text += f" = {py_default(p.default)}"
        params.append(text)
    try:
        ret = py_type(b.ret, "out", aliases, used)
    except UnknownType as exc:
        raise SystemExit(
            f"{b.file.name}:{b.line}: {b.name} returns Rust type {exc.args[0]!r} with no "
            "Python mapping; teach scripts/generate_python_stubs.py:py_type about it"
        ) from None
    one_line = f"{indent}def {b.name}({', '.join(params)}) -> {ret}:"
    if len(one_line) <= 99:
        head = one_line
    else:
        head = (
            f"{indent}def {b.name}(\n"
            + "".join(f"{indent}    {p},\n" for p in params)
            + f"{indent}) -> {ret}:"
        )
    doc = _docstring(b.doc, indent + "    ")
    return head + ("\n" + doc if doc else " ...\n")


def render_class(c: PyClass, aliases: dict[str, str], used: set[str]) -> str:
    # Without #[pyclass(subclass)] a PyO3 class is final. A subclassable one has a native
    # layout, so it cannot share a subclass with another native base (PEP 800).
    if c.subclassable:
        used.add("disjoint_base")
        decorators = "@disjoint_base\n"
    else:
        used.add("final")
        decorators = "@final\n"
    out = [f"{decorators}class {c.name}:\n"]
    doc = _docstring(c.doc, "    ")
    if doc:
        out.append(doc + "\n")
    if c.ctor is not None:
        ctor = Binding(**{**c.ctor.__dict__, "ret": "Self", "doc": ""})
        out.append(render_function(ctor, aliases, used, receiver="cls", indent="    "))
    for m in c.methods:
        out.append(render_function(m, aliases, used, receiver="self", indent="    "))
    for prop in c.properties:
        try:
            ret = py_type(prop.ret, "out", aliases, used)
        except UnknownType as exc:
            raise SystemExit(
                f"{c.file.name}:{prop.line}: {c.name}.{prop.name} returns Rust type "
                f"{exc.args[0]!r} with no Python mapping; teach py_type about it"
            ) from None
        pdoc = _docstring(prop.doc, "        ")
        out.append(
            f"    @property\n    def {prop.name}(self) -> {ret}:"
            + ("\n" + pdoc if pdoc else " ...\n")
        )
    if len(out) == 1:
        out.append("    ...\n")
    return "\n".join(out)


def render_module(module: str, bindings: list[Binding], classes: list[PyClass]) -> str:
    helper_aliases = type_aliases(BINDINGS / "helpers.rs")
    used: set[str] = set()
    funcs: list[str] = []
    for c in sorted(classes, key=lambda x: x.name):
        aliases = {**helper_aliases, **type_aliases(c.file)}
        funcs.append(render_class(c, aliases, used))
    for b in sorted(bindings, key=lambda x: x.name):
        aliases = {**helper_aliases, **type_aliases(b.file)}
        funcs.append(render_function(b, aliases, used))
    imports: list[str] = []
    if "Sequence" in used or "Mapping" in used:
        names = ", ".join(sorted(n for n in ("Mapping", "Sequence") if n in used))
        imports.append(f"from collections.abc import {names}")
    typing_names = sorted(n for n in ("Any", "Self", "final") if n in used)
    if typing_names:
        imports.append(f"from typing import {', '.join(typing_names)}")
    if "disjoint_base" in used:
        imports.append("\nfrom typing_extensions import disjoint_base")
    if "polars" in used:
        imports.append("\nimport polars")
    head = HEADER + '"""Stubs for ``openquant._core.' + module + '``."""\n\n'
    if imports:
        head += "\n".join(imports) + "\n\n"
    # PyO3's add_function and add_class record every function and class in __all__.
    names = sorted([b.name for b in bindings] + [c.name for c in classes])
    head += "__all__ = [\n" + "".join(f'    "{n}",\n' for n in names) + "]\n\n"
    return head + "\n".join(funcs)


def render_init(modules: list[str]) -> str:
    lines = [HEADER, '"""Stubs for the compiled extension ``openquant._core``."""\n\n']
    for m in modules:
        lines.append(f"from . import {m} as {m}\n")
    lines.append("\n")
    # add_submodule records each submodule in __all__ (once per registration).
    lines.append("__all__ = [\n" + "".join(f'    "{m}",\n' for m in modules) + "]\n")
    return "".join(lines)


def ruff_format(text: str, name: str) -> str:
    """Pass a stub through `ruff format`, so the committed stubs satisfy the lint gate."""
    ruff = shutil.which("ruff") or str(Path(sys.executable).with_name("ruff"))
    try:
        done = subprocess.run(
            [ruff, "format", "--stdin-filename", name, "-"],
            input=text,
            capture_output=True,
            text=True,
            check=True,
            cwd=ROOT,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise SystemExit(f"ruff format failed on {name} (install the dev group): {exc}") from exc
    return done.stdout


def generate() -> dict[Path, str]:
    by_module: dict[str, list[Binding]] = {}
    for b in all_bindings():
        by_module.setdefault(b.module, []).append(b)
    classes_by_module: dict[str, list[PyClass]] = {}
    for c in all_classes():
        by_module.setdefault(c.module, [])
        classes_by_module.setdefault(c.module, []).append(c)
    files = {
        OUT_DIR / f"{m}.pyi": render_module(m, bs, classes_by_module.get(m, []))
        for m, bs in sorted(by_module.items())
    }
    files[OUT_DIR / "__init__.pyi"] = render_init(sorted(by_module))
    return {p: ruff_format(text, str(p.relative_to(ROOT))) for p, text in files.items()}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if the stubs are stale")
    args = parser.parse_args()
    files = generate()
    existing = set(OUT_DIR.glob("*.pyi")) if OUT_DIR.exists() else set()
    if args.check:
        stale = [p for p, text in files.items() if not p.exists() or p.read_text() != text]
        extra = sorted(existing - set(files))
        if stale or extra:
            for p in stale:
                print(f"stale stub: {p.relative_to(ROOT)}")
            for p in extra:
                print(f"orphan stub (no bindings): {p.relative_to(ROOT)}")
            print("run: python scripts/generate_python_stubs.py")
            return 1
        print(f"python stubs up to date ({len(files)} files)")
        return 0
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for p in existing - set(files):
        p.unlink()
    for p, text in files.items():
        if not p.exists() or p.read_text() != text:
            p.write_text(text)
    print(f"wrote {len(files)} stub files to {OUT_DIR.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
