// Generated by scripts/afml_docs_loop.py export. Do not edit manually.
export const afmlDocsState = {
  "generatedAt": "2026-02-08T21:38:20+00:00",
  "chapters": [
    {
      "chapter": "CHAPTER 2",
      "theme": "Event-driven market data",
      "status": "done",
      "chunkCount": 11,
      "sections": [
        {
          "id": "chapter-2-data_structures",
          "module": "data_structures",
          "slug": "data-structures",
          "status": "done"
        },
        {
          "id": "chapter-2-filters",
          "module": "filters",
          "slug": "filters",
          "status": "done"
        },
        {
          "id": "chapter-2-etf_trick",
          "module": "etf_trick",
          "slug": "etf-trick",
          "status": "done"
        }
      ]
    },
    {
      "chapter": "CHAPTER 3",
      "theme": "Labeling and target engineering",
      "status": "done",
      "chunkCount": 56,
      "sections": [
        {
          "id": "chapter-3-labeling",
          "module": "labeling",
          "slug": "labeling",
          "status": "done"
        },
        {
          "id": "chapter-3-bet_sizing",
          "module": "bet_sizing",
          "slug": "bet-sizing",
          "status": "done"
        }
      ]
    },
    {
      "chapter": "CHAPTER 4",
      "theme": "Sample uniqueness and weighting",
      "status": "done",
      "chunkCount": 13,
      "sections": [
        {
          "id": "chapter-4-sampling",
          "module": "sampling",
          "slug": "sampling",
          "status": "done"
        },
        {
          "id": "chapter-4-sample_weights",
          "module": "sample_weights",
          "slug": "sample-weights",
          "status": "done"
        },
        {
          "id": "chapter-4-sb_bagging",
          "module": "sb_bagging",
          "slug": "sb-bagging",
          "status": "done"
        }
      ]
    },
    {
      "chapter": "CHAPTER 5",
      "theme": "Stationarity and memory",
      "status": "done",
      "chunkCount": 2,
      "sections": [
        {
          "id": "chapter-5-fracdiff",
          "module": "fracdiff",
          "slug": "fracdiff",
          "status": "done"
        }
      ]
    },
    {
      "chapter": "CHAPTER 7",
      "theme": "Leakage-aware validation",
      "status": "done",
      "chunkCount": 39,
      "sections": [
        {
          "id": "chapter-7-cross_validation",
          "module": "cross_validation",
          "slug": "cross-validation",
          "status": "done"
        }
      ]
    },
    {
      "chapter": "CHAPTER 8",
      "theme": "Feature diagnostics",
      "status": "done",
      "chunkCount": 22,
      "sections": [
        {
          "id": "chapter-8-feature_importance",
          "module": "feature_importance",
          "slug": "feature-importance",
          "status": "done"
        },
        {
          "id": "chapter-8-fingerprint",
          "module": "fingerprint",
          "slug": "fingerprint",
          "status": "done"
        }
      ]
    },
    {
      "chapter": "CHAPTER 10",
      "theme": "Position sizing",
      "status": "done",
      "chunkCount": 16,
      "sections": [
        {
          "id": "chapter-10-bet_sizing",
          "module": "bet_sizing",
          "slug": "bet-sizing",
          "status": "done"
        }
      ]
    },
    {
      "chapter": "CHAPTER 14",
      "theme": "Backtest diagnostics",
      "status": "done",
      "chunkCount": 31,
      "sections": [
        {
          "id": "chapter-14-backtest_statistics",
          "module": "backtest_statistics",
          "slug": "backtest-statistics",
          "status": "done"
        },
        {
          "id": "chapter-14-risk_metrics",
          "module": "risk_metrics",
          "slug": "risk-metrics",
          "status": "done"
        }
      ]
    },
    {
      "chapter": "CHAPTER 16",
      "theme": "Portfolio construction",
      "status": "done",
      "chunkCount": 41,
      "sections": [
        {
          "id": "chapter-16-hrp",
          "module": "hrp",
          "slug": "hrp",
          "status": "done"
        },
        {
          "id": "chapter-16-hcaa",
          "module": "hcaa",
          "slug": "hcaa",
          "status": "done"
        },
        {
          "id": "chapter-16-onc",
          "module": "onc",
          "slug": "onc",
          "status": "done"
        },
        {
          "id": "chapter-16-cla",
          "module": "cla",
          "slug": "cla",
          "status": "done"
        },
        {
          "id": "chapter-16-portfolio_optimization",
          "module": "portfolio_optimization",
          "slug": "portfolio-optimization",
          "status": "done"
        }
      ]
    },
    {
      "chapter": "CHAPTER 17",
      "theme": "Regime detection",
      "status": "done",
      "chunkCount": 22,
      "sections": [
        {
          "id": "chapter-17-structural_breaks",
          "module": "structural_breaks",
          "slug": "structural-breaks",
          "status": "done"
        }
      ]
    },
    {
      "chapter": "CHAPTER 18",
      "theme": "Entropy methods",
      "status": "done",
      "chunkCount": 19,
      "sections": [
        {
          "id": "chapter-18-microstructural_features",
          "module": "microstructural_features",
          "slug": "microstructural-features",
          "status": "done"
        }
      ]
    },
    {
      "chapter": "CHAPTER 19",
      "theme": "Microstructure estimators",
      "status": "done",
      "chunkCount": 74,
      "sections": [
        {
          "id": "chapter-19-microstructural_features",
          "module": "microstructural_features",
          "slug": "microstructural-features",
          "status": "done"
        },
        {
          "id": "chapter-19-codependence",
          "module": "codependence",
          "slug": "codependence",
          "status": "done"
        }
      ]
    }
  ]
} as const;
export type AfmlDocsState = typeof afmlDocsState;
